<?php

namespace sf\RestBundle\Repository;

/**
 * CategoryJobMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryJobMapRepository extends \Doctrine\ORM\EntityRepository
{
}
