<?php

namespace sf\RestBundle\Repository;

/**
 * JobRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRateRepository extends \Doctrine\ORM\EntityRepository
{
}
