<?php

namespace sf\RestBundle\Repository;

/**
 * JobUserMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobUserMapRepository extends \Doctrine\ORM\EntityRepository
{
}
