<?php

namespace sf\RestBundle\Repository;

/**
 * UserDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
