sf_rest:
    resource: "@sfRestBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type: rest
    resource: sf\RestBundle\Controller\UsersController
    
Default:
    type: annotation
    resource: sf\RestBundle\Controller\DefaultController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
# MISC
login_check:
    path: /api/login_check

acme_api_ping:
    pattern: /api/ping
    defaults: { _controller: 'sfRestBundle:Users:ping' }
    requirements:
        _method: HEAD|GET

# REST
#acme_api_page:
#    type:           rest
#    resource:       sf\RestBundle\Controller\Rest\PageController
#fos_oauth_server_token:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
