sf_rest:
    resource: "@sfRestBundle/Controller/"
    type:     annotation
    prefix:   /
    
users:
    type: rest
    resource: "@sfRestBundle/Controller/UsersController"
    
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
