#sf_rest:
#    resource: "@sfRestBundle/Controller/"
#    type:     annotation
#    prefix:   /

rest_api:
    resource: "@sfRestBundle/Resources/config/routing.yml"
    prefix:   /api
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# REST
#acme_api_page:
#    type:           rest
#    resource:       sf\RestBundle\Controller\Rest\PageController
#fos_oauth_server_token:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
