sf_rest:
    resource: "@sfRestBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type: rest
    resource: sf\RestBundle\Controller\UsersController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
