parameters:
    rest_api.event.jwt_response_listener.class: sf\RestBundle\EventListener\JWTResponseListener
    rest_api.event.jwt_created_listener.class: sf\RestBundle\EventListener\JWTCreatedListener
    rest_api.event.jwt_decoded_listener.class: sf\RestBundle\EventListener\JWTDecodedListener

services:
    rest_api.event.jwt_response_listener:
        class: %rest_api.event.jwt_response_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    rest_api.event.jwt_created_listener:
        class: %rest_api.event.jwt_created_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    rest_api.event.jwt_decoded_listener:
        class: %rest_api.event.jwt_decoded_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }
